### ISSUE TITLE
Should () implement Fail

### ISSUE THREAD

**Issue by alkis** [withoutboats/failure#103]
And `From<()> for Error` should panic?

This would be convenient when use has two streams:

`Stream<Item=u64, Error:StdError>` and `Stream<Item=u64, ()>` and wants to select on them:

`stream1.from_err().select(stream2.from_err())` should compile but currently it does not.

**Comment by withoutboats** [comment]
This is not something we can do in failure because of coherence; you'd have to convince std to implement `StdError` for `()`.

**Comment by vitvakatu** [comment]
FYI, From traits can't panic, it's bad

**Comment by alkis** [comment]
@withoutboats can you provide a little bit more context about coherence? (need to fuel my curiousity)

@vitvakatu  `From<()> for Error` would never be called though, right? That's the whole point of specifying `Error=()`.
