### ISSUE TITLE
Best way to interop with crates using `error-chain`?

### ISSUE THREAD

**Issue by luser** [withoutboats/failure#109]
I finally found a reason to try out `failure` and I like it so far! I appreciate not having to remember the special syntax for the `error_chain` macro. The biggest stumbling block I've hit so far is that a lot of crates do already use `error-chain` for their error types, and those don't seem to be automatically convertible to `failure::Error`. 

I created [a simple example](https://github.com/luser/failure-errorchain) with `error-chain` 0.11.0 and `failure` 0.1.1 and trying to use the `?` operator on a function that returns an `error-chain` created error produces:

```
error[E0277]: the trait bound `std::error::Error + std::marker::Send + 'static: std::marker::Sync` is not satisfied
  --> src/lib.rs:23:5
   |
23 |     a::foo()?;
   |     ^^^^^^^^^ `std::error::Error + std::marker::Send + 'static` cannot be shared between threads safely
   |
   = help: the trait `std::marker::Sync` is not implemented for `std::error::Error + std::marker::Send + 'static`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<std::error::Error + std::marker::Send + 'static>`
   = note: required because it appears within the type `std::boxed::Box<std::error::Error + std::marker::Send + 'static>`
   = note: required because it appears within the type `std::option::Option<std::boxed::Box<std::error::Error + std::marker::Send + 'static>>`
   = note: required because it appears within the type `error_chain::State`
   = note: required because it appears within the type `a::error::Error`
   = note: required because of the requirements on the impl of `failure::Fail` for `a::error::Error`
   = note: required because of the requirements on the impl of `std::convert::From<a::error::Error>` for `failure::Error`
   = note: required by `std::convert::From::from`
```

What's the best way to handle this situation?

**Comment by Michael-F-Bryan** [comment]
This is what I'm currently using in one of my projects. It's a band-aid fix at best, but it works pretty well for the time being while we're waiting for a better solution.

```rust
trait ResultExt<T, E> {
    fn sync(self) -> Result<T, SyncFailure<E>>
    where
        Self: Sized,
        E: ::std::error::Error + Send + 'static;
}

impl<T, E> ResultExt<T, E> for Result<T, E> {
    fn sync(self) -> Result<T, SyncFailure<E>>
    where
        Self: Sized,
        E: ::std::error::Error + Send + 'static,
    {
        self.map_err(SyncFailure::new)
    }
}
```

The using it:

```rust
    let mut builder = EpubBuilder::new(ZipLibrary::new().sync()?).sync()?;

    builder.metadata("generator", "mdbook-epub").sync()?;

    if let Some(title) = ctx.config.book.title.clone() {
        builder.metadata("title", title).sync()?;
    }
```

**Comment by withoutboats** [comment]
We provide `SyncFailure` to solve this problem, @Michael-F-Bryan's code is a nice little glue code to maek it much easier to use. This is a really frustrating (and in my opinion, mistaken) part of error-chain, that it makes `!Sync` errors.

I have a PR to fix this in error chain, but its also a breaking change in error-chain, and I'm not sure how many people will upgrade to the new version of error-chain once its merged.

**Comment by luser** [comment]
Thanks! :heart:
