### ISSUE TITLE
thread '<unknown>' has overflowed its stack

### ISSUE THREAD

**Issue by bbigras** [withoutboats/failure#126]
I got `thread '<unknown>' has overflowed its stack` when trying to println!() an error.

I'm not even sure if it's related to failure. Not sure what I can do to debug.

gdb
```
Thread 6 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 12080.0x1370]
0x00007ff76727d02a in ?? ()
(gdb) bt
#0  0x00007ff76727d02a in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

failure = "0.1.1"
nightly-x86_64-pc-windows-msvc (default)
rustc 1.25.0-nightly (61452e506 2018-01-09)

**Comment by bbigras** [comment]
My problem might be related to using a modified version of the nom crate that was usable with error-chain.
https://github.com/bbigras/nom/commit/5bde05981911f3332e9eb864a68b03061cf29b06

**Comment by withoutboats** [comment]
Not sure that there's anything I can do to help. :( I don't know how failure could've caused this & I don't have much insight from the info you posted. Hope you were able to make progress!
