### ISSUE TITLE
Context::with_err is private

### ISSUE THREAD

**Issue by U007D** [withoutboats/failure#13]
Perhaps I'm doing this wrong, but should `Context::with_err` be private?

In attempting to follow the best-practices advice from issue #6, I am attempting to implement my custom error type as a `struct`, with `enum ErrorKind` variants.

I suppose I'm *not* following best practices advice by loading a variant with a cause (advice on how best to do this is welcome), but the way I attempted to do this requires access to the Context::with_err static constructor method, which is private.  Is this intentional?

Here is my code:
```rust
use failure::Context;
use assayer::Error as AssayerError;

#[derive(Debug, Fail)]
#[fail(display = "{}", inner)]
pub struct Error {
    inner: Context<ErrorKind>,
}

#[derive(Debug, Fail)]
enum ErrorKind {
    #[fail(display = "argument validation error")]
    #[cause] ArgValidation(AssayerError),
}

impl From<AssayerError> for Error {
    fn from(err: AssayerError) -> Error {
        Error { inner: Context::with_err(ErrorKind::ArgValidation(err), err), }
    }
}
```
The above yields ``error[E0624]: method `with_err` is private``.
If I am using `Failure` wrong, my apologies.  Suggestions/advice welcome!

**Comment by cramertj** [comment]
There's a [context](https://github.com/withoutboats/failure/blob/master/src/lib.rs#L107) method on the `Fail` trait that you can use-- it calls `Context::with_err` internally.

**Comment by U007D** [comment]
Thanks, @cramertj, I'll give that a shot.

**Comment by withoutboats** [comment]
Yep, the intent is you create a context with `Fail::context` or (if you want to create one without an underlying error) with `Context::new`. `Context::with_err` is an implementation detail.

**Comment by U007D** [comment]
I guess I'm confused.  In `impl From... for Error` above, I am wrapping a foreign error (which is not `Fail`); 
 I don't know how can I initialize `Error::inner` using `Fail::context()`, without a `Fail` instance available.   Any ideas?

I'm also a bit puzzled on the asymmetry between using `Fail::context` for context **with** underlying error and `Context::new` for context **without** underlying error.  I've no doubt there are valid implementation reasons for the split, but I wonder if the ergonomics could be improved by supporting both scenarios under `Fail` with `Fail::context` for context **without** an underlying error and `Fail::context_err` for context **with** an underlying error (or something similar).

**Comment by U007D** [comment]
Ah, nvm.  I see now that Fail::context is supposed to be used in error's throw path, rather than at its declaration point.  That  clears up both points of confusion I was under.
