### ISSUE TITLE
Boxed causes

### ISSUE THREAD

**Issue by letheed** [withoutboats/failure#132]
I sometimes wrap my errors in Boxes so they don't get too large, but the following fails. I'm guessing that's because there's no `impl<T: Fail> Fail for Box<T>`. Is it just missing or is there a good reason for that?

```rust
#[derive(Fail, Debug)]
enum EnumError {
    #[fail(display = "An IO error occurred.")]
    IoError(#[cause] Box<io::Error>),
}
```

**Comment by withoutboats** [comment]
There's not a good reason for it, but it might not be coherent. If you want to see if it compiles & make a PR I would welcome it :-D.

**Comment by letheed** [comment]
It conflicts with the blanket `impl<E: StdError + Send + Sync + 'static> Fail for E {}`, which applies to Box since `impl<T: Error> Error for Box<T>`.

**Comment by withoutboats** [comment]
ugh, quite frustrating :-(.

However, that implies that `Box<io::Error>` should implement `Fail`, since it implements `Error`. Need to investigate further why this isn't working for you.

**Comment by letheed** [comment]
Ugh, that's my mistake. I presented a simplified case, but yes it does work in the specific case of `io::Error` since it's `error::Error`. It does fail like I described for my own error enums though since they're not `error::Error`. (Well they were but getting rid of it is kinda the point...)

**Comment by letheed** [comment]
Specialization might allow that, but that's unstable for now. Another solution would be to hack it directly in derive_failure, at least until specialization stabilizes.

**Comment by withoutboats** [comment]
I think @mystor had a PR to add this impl to the derive for `Fail`.

**Comment by withoutboats** [comment]
Yes, #112. So it should be in the next release :)

**Comment by letheed** [comment]
Hmm, it's not in derive but yes, that's an improvement. That's limited to trait objects though, so we'll need to add a cast to the `From` impls.

**Comment by withoutboats** [comment]
Oh, sorry, I'm thinking of withoutboats/failure-derive#6, which hasn't been merged yet.

**Comment by letheed** [comment]
Wonderful! Thank you
