### ISSUE TITLE
Consider renaming "context" to "cause"

### ISSUE THREAD

**Issue by aturon** [withoutboats/failure#169]
The fact that we separate these two names right now can lead to confusion. AIUI, the purpose of a context is precisely to add to the cause chain.

**Comment by aturon** [comment]
Sorry, I didn't mean it quite that literally. What I meant was like:

- `with_cause` to add a cause
- `Cause` for the wrapper type

etc

**Comment by withoutboats** [comment]
That seems backwards. *self* is the cause of the context, not the information you pass to it (the context).

Also, ResultExt already has a `context` and `with_context` set (the latter taking a lazily evaluated closure); how would `with_cause` translate to that API?

Context is not the only way to build up a cause chain, its just a convenient & dynamic solution that doesn't require creating custom types. I don't think we should suggest a 1:1 identification between context and cause.

**Comment by aturon** [comment]
Makes sense, thanks!
