### ISSUE TITLE
Let's bikeshed on names!

### ISSUE THREAD

**Issue by HadrienG2** [withoutboats/failure#19]
I like the general design of this crate a lot. I think that Fail is a solid improvement over the existing Error trait, and that the proposed Error struct is a good default mechanism for error handling (though not a universal approach, since it relies on dynamic memory allocation, we'll probably continue to need mechanisms for generating a One True Error Type for some use cases).

That being said, I would prefer for my error handling code not to be riddled with internet meme references, so it would be nice if there were a more "english" name like Failure for the trait that error types need to implement.

And on a related note, there is the question of whether we could find less synonymous names than "Error" and "Fail(ure)" in order to more easily discriminate which of the two is a trait and which is a concrete type. This is especially true since if this crate gets popular, we would enter a transition period where people's crates manipulate two kinds of Error, one of which is a trait (std::error::Error) and one of which is a struct (failure::Error). This could get confusing quickly.

With these two considerations in mind, how about naming the trait Error and the struct AnyError? Error is consistent with the std naming convention, and allows for a smooth migration if the trait is eventually merged into the standard library, whereas AnyError should hint quite well at the fact this this is a type that can hold any error (with a subtle hint at the Any trait for type erasure).

**Comment by withoutboats** [comment]
According to Rust's style guides, best practice is to name traits verbs (e.g. Read, Write, Display) and types nouns (e.g. Result, String, HashMap). Fail is an English verb and not intended to be a reference to a meme.

**Comment by withoutboats** [comment]
We did consider Error/AnyError as an alternative prior to publicizing this, but I'm pretty confident that would not be preferable.

**Comment by HadrienG2** [comment]
I did not know about this trait naming guideline, but it seems like in addition to being somewhat arbitrary (why should a trait always be named after an action?), it is not really applied in practice.

Just consider the standard library traits: you have Any, AsRef/AsMut, (Partial)Eq, Error, Fn, From/Into, Hasher, Iterator (Partial)Ord, Sized... It does seem like we did very well without the constraint that everything be a verb so far.

**Comment by withoutboats** [comment]
Its true that it hasn't been followed consistently (though "Ord[er]" and "Error" are technically verbs). I don't even like it that much, but since it is the recommendation I'm inclined to follow it.

**Comment by HadrienG2** [comment]
Well, let's see if I'm the only one bothered by this naming convention or if others have better proposals, then. I will gladly admit to being terrible at naming things, it's just that for reasons described above, I have the impression that there has to be a better name somewhere waiting to be found.

**Comment by withoutboats** [comment]
I'm open to renaming Fail if there is a better name out there, but I'm pretty committed to Error so that the obvious thing of making the Err variant of Result an Error will Just Work.

**Comment by U007D** [comment]
@HadrienG2 I agree that the trait vs. struct name collision is (and will continue to be) a source of confusion (I've run into this myself in the not-too-distant past).  I also agree that some of the guideline choices seem questionable.

With that, my 2¢ is in agreement with @withoutboats that the best way forward (ie. best way to not introduce yet more confusion over and above what we already have) is to adhere to the guidelines, such as they are.

**Comment by repax** [comment]
IIRC, the motivation for that guideline was to have short trait names, e.g. `Copy` instead of `Copyable`. Personally, I think adjectives are a better fit for traits names. Verbs makes sense for functions.

**Comment by withoutboats** [comment]
This is the only issue opened so far that would be a breaking change to follow up on after the 0.1 release, so its the one we need to hash out ASAP. If you have alternative names, speak now or forever hold your peace. :-)

**Comment by DorianListens** [comment]
I’m a fan of both Fail and Error, for what it’s worth. I think the naming guidelines are worth following for consistency if nothing else, and the confusion over Error is probably worth it to simplify the common case.

**Comment by m4b** [comment]
This is somewhat related but do you plan to use `-` or underscore in crate name (for derive) ?

Also I thought derive_fail was unusual (as opposed to fail_derive)

Also the crate will be named failure or fail?

**Comment by withoutboats** [comment]
The crate name is failure. The derive crate will probably be renamed `failure_derive` since this is the most common naming scheme for derive crates.

**Comment by m4b** [comment]
Yes please the second, had to lookup again that it was derive_fail instead of failure. It also matches serde, etc, and this way can easily see all the deriving crates at a glance

**Comment by troiganto** [comment]
Just throwing this out, but since the main purpose of the trait in question seems to be to universally 'cast' any error to the `failure::Error` type, would `IntoError` be a fitting name? The name seems to have some precedent in the standard library (`IntoIterator` comes to mind).

**Comment by withoutboats** [comment]
Planning to release this tomorrow afternoon (PST, aka about 10 to 12 hours from now). Since I don't plan to make breaking changes at least for the rest of the year I'm going to close this.

Changed the name of the derive crate to failure_derive but otherwise feel pretty happy with the original names. Thanks for the discussion though.

@troiganto Sorry I forgot to reply to your comment. `Fail` is useful separate from `Error`; though returning `Error` is often a good idea, there are use cases in which you don't want to do that. So I don't want to suggest that the only reason to implement the trait is to cast your type into `Error`.

**Comment by troiganto** [comment]
That's a fair point. FWIW, I switched the application I'm working on from `quick-error` to `failure` yesterday. The refactor was straight-forward, removed a ton of boilerplate, and and all compiler warnings/errors afterwards were about missing or unused `use`s. So I'm very excited for the next release!
