### ISSUE TITLE
Contradictory code in readme

### ISSUE THREAD

**Issue by jimrybarski** [withoutboats/failure#21]
In the code example in README.md:

```
// All we do is derive Fail and Display for it, no other "magic."
#[derive(Debug, Fail)]
enum ToolchainError {
```
Should the comment say "Fail and Debug" or should it be `#[derive(Display, Fail)]`?

**Comment by withoutboats** [comment]
Its a bit confusing, but its referring to the fact that deriving `Fail` will generate both a `Fail` and a `Display` implementation. It could be rewritten.

**Comment by withoutboats** [comment]
I tried to clarify the text in the README.
