### ISSUE TITLE
Documentation Conventions

### ISSUE THREAD

**Issue by keeperofdakeys** [withoutboats/failure#23]
I've noticed that the documentations for this crate uses the convention ``` `Fail`ure ``` in place of the word `failure`. I'm finding this a bit hard to read, so I was wondering if you'd accept a PR to change it to just `failure` in the appropriate places.

**Comment by withoutboats** [comment]
It was based on what I thought was a convention of calling "readers" "`Read`ers" on io::Read, but I've discovered now only 1 method uses that convention and everything else just says "readers." I'd accept a PR to change it if its hard to read.

I think the convention is to call a type that implements Fail a "failure" though, to avoid confusion with the Error type.

**Comment by withoutboats** [comment]
Fixed by #24
