### ISSUE TITLE
Idea: Automatically add context-field when converting an error

### ISSUE THREAD

**Issue by nielsle** [withoutboats/failure#27]
It could be great to use a decorator to automatically add one or more fields when converting an error to another error. Perhaps it could look like this

~~~ rust
#[derive(Fail, Debug)]
struct ParseError {
    filename: String, 
    error: MyError
}

// do_stuff returns a MyError, but the add_fields decorator causes the error to be 
// converted in to a ParseError adding a filename.to_owned() as a field.
#[fail(add_fields = [filename])]
fn read_file(filename: &str) -> Result<(), ParseError>{
    do_stuff(filename)?;
    do_stuff(filename)?;
    Ok(())
}
~~~

I am not sure if the  above is actually doable, and the syntax probably needs tweaking, but it could be really useful to have something to this effect.

**Comment by tailhook** [comment]
Isn't it just the following?
```
fn read_file(filename: &str) -> Result<(), Context<String>> {
  _read_file(filename).context(filename.to_string())
}
fn _read_file(filename: &str) -> Result<(), ParseError>{
    do_stuff(filename)?;
    do_stuff(filename)?;
    Ok(())
}
```
Or maybe you can even use lambda (not sure it can actually derive a type for lambda):
```
fn read_file(filename: &str) -> Result<(), Context<String>> {
    (|| {
        do_stuff(filename)?;
        do_stuff(filename)?;
        Ok(())
    })().context(filename.to_string())
}
```

**Comment by nielsle** [comment]
hmm.. I agree that these approaches work. 

Feel free to close the issue if you don't think that the feature is needed or if it is out of scope for the failure crate.

**Comment by withoutboats** [comment]
The syntax you proposed isn't possible on stable, and seems very difficult to get right because of the amount of implicit information it. We do intend to just support the `.context()` adapter as a way of injecting context.
