### ISSUE TITLE
Test the no_std mode

### ISSUE THREAD

**Issue by withoutboats** [withoutboats/failure#30]
It would be great to add to .travis.yml an additional test run which does `cargo test --no-default-features` (turning off the `std` feature) on stable. The 4 existing test runs should still use std.

Not sure how to do this, but I'm sure its possible if someone reads the Travis docs. :)

**Comment by Pratyush** [comment]
`serde` has a [test](https://github.com/serde-rs/serde/tree/master/test_suite/no_std) to check whether `serde` and `serde_derive` compile on `no_std`. Their `.travis.yml` invokes [this script](https://github.com/serde-rs/serde/blob/master/travis.sh). Of course, they just test whether things compile or not. Does that suffice for `failure`'s purposes?
