### ISSUE TITLE
Accessing structs in in derived display appears to cause a failure.

### ISSUE THREAD

**Issue by Plasticcaz** [withoutboats/failure#31]
I am currently writing a parser for fun, and I decided to give the failure crate a go.

In my attempts to try and provide as much information as possible in errors, I want to pass the offending token in my struct, and get information out of that token.

Here is the offending code:

    #[derive(Debug, Fail)]
    pub enum ParseError {
        #[fail(display = "Expecting a token to exist, but no token was found.")]
        NoTokenFound,
        #[fail(display = "{}: Expected a token of type {:?}, but got a token of type {:?}.", location,
           expected, got.ttype)]
        UnexpectedToken {
            location: Location,
            got: Token,
            expected: TokenType,
        },
    }

When I change the reference to got.ttype to simply "got", it works fine.

Could we enable accessing struct fields, or is there a reason we must avoid using it?

**Comment by withoutboats** [comment]
Currently the derive is limited to what is allowed in attributes, which does not include methods or field accesses. The derive will improve when attribute syntax becomes more flexible (which it will soon).

**Comment by Plasticcaz** [comment]
Thanks for replying. Yeah, the solution for now is to implement display for Token. In the future I will probably want to control what is displayed in the Error, but I guess by then the attribute syntax will have landed.

Thanks again.
