### ISSUE TITLE
Why Context isn't generic over the error?

### ISSUE THREAD

**Issue by tailhook** [withoutboats/failure#33]
If context accepts a generic displayable thing as a context I see no inherent cost at adding another generic for error too, i.e. `Context<D: Display, E: Fail>`. Or is it somehow related to how question-mark/carrier work?

**Comment by withoutboats** [comment]
Its necessary to make context object safe and to allow it to be used as the return type for functions returning multiple kinds of errors with additional context. This was an intentional choice.
