### ISSUE TITLE
Provide a standard way of printing/formatting an Error / Fail

### ISSUE THREAD

**Issue by sdroege** [withoutboats/failure#34]
It would be nice if there was some standard way of printing/formatting an Error or something implementing Fail.

Something that takes a &Write, maybe with a convenience helper that takes stderr/stdout, and prints the error itself, its description, its backtrace, and does the same for all the causes of it. Maybe parts of this should be configurable (don't print backtraces, don't recurse into causes).

**Comment by withoutboats** [comment]
Errors implement `Debug` and `Display`. The backtrace is only printed in the `Debug` output. This is the standard way to print an error.

**Comment by sdroege** [comment]
While the `Debug` output contains all this, it is not very nicely formatted. It's basically the definition of `Error` with curly braces and everything, and the contents of its fields printed, like what `Debug` usually does. Something more along the lines of how e.g. Java or most JS implementations print exceptions would seem useful.
