### ISSUE TITLE
Rename Compat::inner to into_inner

### ISSUE THREAD

**Issue by dtolnay** [withoutboats/failure#4]
This is the convention for such methods in the standard library ([`BufReader::into_inner`](https://doc.rust-lang.org/std/io/struct.BufReader.html#method.into_inner)) and widely used crates ([`flate2::read::GzEncoder::into_inner`](https://docs.rs/flate2/0.2.17/flate2/read/struct.GzEncoder.html#method.into_inner)).

**Comment by withoutboats** [comment]
Fixed, thanks! :)
