### ISSUE TITLE
Cannot lazily construct `Context`

### ISSUE THREAD

**Issue by epage** [withoutboats/failure#40]
Error chain's `chain_err` takes a `Fn` so it will only be evaluated in the error case.
```rust
    fn process_collection() -> Result<()> {
        let path = "non-existent-file";
        process_file(path).chain_err(|| format!("Processing {}", path))
    }
```

Unless I've misread things, `Context` can't.  It takes a `Display`
```rust
    fn process_collection() -> Result<(), Error> {
        let path = "non-existent-file";
        process_file(path).context(format!("Processing {}", path))?;
        Ok(())
    }
```

Another use case where we might want for it to be lazy: `.clone()`-ing the object passed to it.

**Comment by tailhook** [comment]
I think there is [`with_context`](https://github.com/withoutboats/failure/blob/master/src/result_ext.rs#L17) for your use case

**Comment by epage** [comment]
Don't have my project around anymore to try this out but I'm assuming it looks like this
```rust
    fn process_collection() -> Result<(), Error> {
        let path = "non-existent-file";
        process_file(path).with_context(|e| format!("Processing {}", path))?;
        Ok(())
    }
```

So seems like this is more of a documentation issue.
- The [book](https://boats.gitlab.io/failure/fail.html#context) doesn't mention this
- The [API docs](https://docs.rs/failure/0.0.1/failure/) don't include `ResultExt`

**Comment by withoutboats** [comment]
Its very bad that the API docs don't include `ResultExt`. I'll try to figure out why that is (it seems to be properly re-exported); if anyone else figures out why please open a PR.

**Comment by tailhook** [comment]
The link above is to docs.rs on version 0.0.1. Docs generated from master branch are okay.

**Comment by withoutboats** [comment]
Oh right :+1:

**Comment by tailhook** [comment]
@withoutboats still it should be mentioned in the book I think.
