### ISSUE TITLE
A method for iterating over causes

### ISSUE THREAD

**Issue by epage** [withoutboats/failure#41]
Currently there is `cause` and `root_cause`.

It'd be nice to have something like `iter_causes` to help in cases like this
```rust
println!("Error: {}", err);
let mut cause = err.cause();
while let Some(c) = cause {
    println!("Caused by: {}", c);
    cause = c.cause();
}
```
to
```rust
println!("Error: {}", err);
for cause in err.iter_causes() {
    println!("Caused by: {}", cause);
}
```

**Comment by withoutboats** [comment]
I'm open to it, but I think not in `0.1`. For now the while let loop is not so bad.

**Comment by epage** [comment]
I'm fine with it being a lower priority

**Comment by withoutboats** [comment]
#54 resolved this issue :)
