### ISSUE TITLE
Best practice to wrap IO error with message?

### ISSUE THREAD

**Issue by eminence** [withoutboats/failure#42]
Let's say I'm doing some IO in a function, where several things can all fail with a `std::io::Error`.  I want to include some message with that error.  What's the best way to do this with `failure`? It looks like a custom error enum is a good way to start, but I'm unsure how to include the underlying `io::Error` as the underlying cause.

```rust

#[derive(Debug, Fail)]
enum MyCustomError {
    #[fail(display = "failed to read username file")]
    UsernameError,

    #[fail(display = "failed to read password file")]
    PasswordError
}

fn run() -> Result<(), MyCustomError> {

  // somehow put this `io::Error` into a MyCustomError::UsernameError
  let u : File = File::open(&username_file)?;

  // somehow put this `io::Error` into a MyCustomError::PasswordError
  let p : File = File::open(&password_file)?;

  Ok(())
}

```

**Comment by withoutboats** [comment]
There's a pattern for what you're looking for which I'm writing the docs for now, but its sort of sketched in #6.
