### ISSUE TITLE
Will errors with lifetimes be supported?

### ISSUE THREAD

**Issue by m4b** [withoutboats/failure#43]
E.g., this fails to compile:

```
#[derive(Fail, Debug)]
pub enum LinkError<'a> {
    #[fail(display = "Undeclared symbolic reference to: {}", _0)]
    Undeclared (&'a str),
}
```

Are there plans to ever support this, or is this not possible due to other constraints?

**Comment by withoutboats** [comment]
Not in 0.1. Fail is bound `Send + Sync + 'static` to be very conservative. Its possible this will be restricted if their is compelling motivation.
