### ISSUE TITLE
Debug and Display impls for provided types

### ISSUE THREAD

**Issue by withoutboats** [withoutboats/failure#5]
I definitely just threw together the Debug and Display impls in this library for types like Error, Context, etc. They should be reviewed for quality and better ways of conveying the same information should be considered and discussed.

**Comment by nielsle** [comment]
Would it make sense to provide `derive_display` as a separate library? I think that it could also be useful for other types than errors.

**Comment by withoutboats** [comment]
Did this review, changed the Debug output for Error.

@nielsle it is certainly possible to create a derive for Display along the same lines as the derive for fail in failure_derive.
