### ISSUE TITLE
Small feedback: the `context` method in `ResultExt`is not a good name.

### ISSUE THREAD

**Issue by divoxx** [withoutboats/failure#58]
For example, it can be very hard for someone to understand the meaning of `context` when reading the following line (specially a person not very familiar with the failure crate):

```rust
let mut file = File::open(cargo_toml_path).context("Missing Cargo.toml")?;
```

Something like `fail_context` would probably be more appropriate and communicate the intent better.

**Comment by withoutboats** [comment]
I don't plan to make breaking changes in the near future, so this name is set in stone for now. Sorry!
