### ISSUE TITLE
`with_context`: expected concrete lifetime, found bound lifetime parameter

### ISSUE THREAD

**Issue by emk** [withoutboats/failure#62]
I'm converting the `next` branch of https://github.com/faradayio/bigml-rs from `error-chain` to `failure`, and I ran into an interesting lifetime issue using `with_context`.

In practice, this library really needs to return detailed context for errors: a message like "404 Not Found" provides totally insufficient debugging help, and we have a policy of wrapping these errors in a context containing the URL that failed.

But since `catch` isn't available on stable Rust, we tend to do this by declaring a local `mkerr` closure, and passing it to `chain_err` like `chain_err(&mkerr)`. Below, I've tried to convert this code to work with `failure`:

```rust
    /// Create a new resource.
    pub fn create<Args>(&self, args: &Args) -> Result<Args::Resource>
        where Args: resource::Args
    {
        let url = self.url(Args::Resource::create_path());
        debug!("POST {} {:#?}", Args::Resource::create_path(), &serde_json::to_string(args));
        let mkerr = |_| CouldNotAccessUrl::new(&url);
        let client = reqwest::Client::new();
        let res = client.post(url.clone())
            .json(args)
            .send()
            .with_context(&mkerr)?;
        Ok(self.handle_response(res).with_context(&mkerr)?)
    }
```

This gives me the compiler error:

```
error[E0271]: type mismatch resolving `for<'r> <&[closure@src/client.rs:61:21: 61:53 url:_] as std::ops::FnOnce<(&'r reqwest::Error,)>>::Output == _`
  --> src/client.rs:66:14
   |
66 |             .with_context(&mkerr)?;
   |              ^^^^^^^^^^^^ expected bound lifetime parameter, found concrete lifetime
   |
   = note: concrete lifetime that was found is lifetime '_#131r

error[E0281]: type mismatch: `[closure@src/client.rs:61:21: 61:53 url:_]` implements the trait `std::ops::Fn<(_,)>`, but the trait `for<'r> std::ops::Fn<(&'r reqwest::Error,)>` is required
  --> src/client.rs:66:14
   |
61 |         let mkerr = |_| CouldNotAccessUrl::new(&url);
   |                     -------------------------------- implements `std::ops::Fn<(_,)>`
...
66 |             .with_context(&mkerr)?;
   |              ^^^^^^^^^^^^
   |              |
   |              expected concrete lifetime, found bound lifetime parameter
   |              requires `for<'r> std::ops::Fn<(&'r reqwest::Error,)>`
   |
   = note: required because of the requirements on the impl of `for<'r> std::ops::FnOnce<(&'r reqwest::Error,)>` for `&[closure@src/client.rs:61:21: 61:53 url:_]`
```

Now, I can work around this trivially. Among many other solutions, I can just write:

```rust
 .with_context(|_| CouldNotAccessUrl::new(&url))?
```

...which works perfectly fine. Indeed, if `catch` were stable, this would be 100% acceptable. But given the current constraints, I wonder if there isn't some tweak to the type of `with_context` that might allow my code to work?

**Comment by withoutboats** [comment]
This is a compiler type inference issue and not something we can change in this crate.

**Comment by emk** [comment]
Thank you for considering this!

I wasn't recommending any specific fix, certainly not one that would require Rust changes. Instead, I was trying to point out a use case `failure` where had worse ergonomics than `error-chain`, and wondering if there were some way to improve this.

It seems like the ideal solution would be `catch`:

```rust
catch {
    f1()?;
    f2()?;
    f3()?;
}.with_context(|_| build_complicated_context(&a, &b, &c))
```

With `error-chain`, I could write:

```rust
let mkerr = || build_complicated_context(&a, &b, &c);
f1().chain_err(&mkerr)?;
f2().chain_err(&mkerr)?;
f3().chain_err(&mkerr)?;
```

My current workaround with `failure` is:

```rust
let mkerr = || build_complicated_context(&a, &b, &c);
f1().with_context(|_| mkerr())?;
f2().with_context(|_| mkerr())?;
f3().with_context(|_| mkerr())?;
```

Another possibility is to split most of my functions into two functions: A worker function which does the work, and a public function which wraps with worker with a `with_context`.
