### ISSUE TITLE
Empty enums don't derive Display

### ISSUE THREAD

**Issue by ExpHP** [withoutboats/failure#63]
```rust
extern crate failure;
#[macro_use]
extern crate failure_derive;

#[derive(Fail, Debug)]
//       ^^^^ error[E0277]: the trait bound `Never: std::fmt::Display` is not satisfied
pub enum Never { }
```

```

  --> lib.rs:17:10
   |
17 | #[derive(Fail, Debug)]
   |          ^^^^ `Never` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
   |
   = help: the trait `std::fmt::Display` is not implemented for `Never`
```

---

(workaround in the interim)

```rust
extern crate failure;
#[macro_use]
extern crate failure_derive;

#[derive(Fail, Debug)]
pub enum Never {
    #[fail(display="wanna")]
    Let(You),
}

#[derive(Debug)] pub struct You(Go);
#[derive(Debug)] pub enum Go { }
```

**Comment by withoutboats** [comment]
You have to include a display attr somewhere for Display to be derived, this is intentional to support people writing custom Display impls while still deriving Fail. For the (uncommon) use case of empty enums which need to impl Fail, just impl Display manually.

**Comment by canndrew** [comment]
Can we revisit this? It's inconsistent for an enum where all variants are marked `#[fail(display = ...)]` to not impl `Display` in the case where the enum has no variants. The argument that `#[derive(Fail)]` needs to support people writing custom `Display` impls doesn't make sense here since there's only one possible `Display` impl you can write for an empty enum.

**Comment by ExpHP** [comment]
To play devil's advocate, I suppose a case could arise in macro codegen where somebody is generating an n-ary error enum along with a Display impl, and this would force them to suppress the Display impl when there are zero variants.  It is much easier to add a missing Display impl for zero variants than would be to suppress generation of a custom impl.

But it does seem like a very rare situation to be concerned about.

**Comment by canndrew** [comment]
Hmm, that's true, I'll take back that it doesn't make sense. I guess it's also inconsistent for an to impl `Display` when none of the variants are marked `#[fail(display = ...)]` just because the enum has no variants...

**Comment by ExpHP** [comment]
One idea is that the enum itself could be optionally marked `#[fail(display)]`.

```rust
// these are all valid

#[derive(Fail, Debug)]
#[fail(display)]
enum MyError {
    #[fail(display = "it broke")]
    Lol,
}

#[derive(Fail, Debug)]
enum MyError {
    #[fail(display = "it broke")]
    Lol,
}

#[derive(Fail, Debug)]
enum MyError {
    Lol,
}
```

* If the `enum` is marked `#[fail(display)]`, then this guarantees a `Display` impl is generated.  (if any variants are missing `#[fail(display)]` annotations, this would be an error)
* `#[fail(display = "stuff")]` is not allowed on the enum.  (*OR*, perhaps it could represent the `_` branch of the `match`, providing a default string to variants that are not annotated)

The expected usage is:

* People writing code normally won't usually write `#[fail(display)]` on the enum (they'll just annotate the variants), but it's something they can do when they have an empty `enum` and they want an automatic impl.
* People writing macros *ought* to annotate the enum with `#[fail(display)]` if they want automatic impls.  (and likewise, they should *not* annotate the enum if they generate their own `Display` impl)

The unfortunate aspect of this is that people can easily write a macro that doesn't annotate the enum, and they might not realize it is broken since they only tested it on 1+ variants.  However, this is already the case; this suggestion merely introduces a solution they can use to fix these macros.
