### ISSUE TITLE
Docs are missing an example on how to return a custom (derived) error

### ISSUE THREAD

**Issue by jbethune** [withoutboats/failure#70]
This is probably a simple issue, but I could not figure it out and I suppose others will also stumble upon it. It would be good if you could include a working example in the documentation for the situation described below: 

I have my own error type which derives from `Fail`. It is unclear to me how it can be automatically converted to a `failure::Error`.

Minimal example:

Cargo.toml:
```
[dependencies]
failure = "0.1.0"
failure_derive = "0.1.0"
```

lib.rs:
```
extern crate failure;

#[macro_use] extern crate failure_derive;

use failure::{Error};

#[derive(Debug,Fail)]
#[fail(display = "This is my error and mine alone!")]
pub struct MyError;

pub struct Foo;

fn foo() -> Result<Foo,Error> {
    Err( MyError{} )
}
```

The error I receive when I am compiling this example:
```
error[E0308]: mismatched types
  --> src/lib.rs:15:10
   |
15 |     Err( MyError{} )
   |          ^^^^^^^^^ expected struct `failure::Error`, found struct `MyError`
   |
   = note: expected type `failure::Error`
              found type `MyError`
```

Thank you so much for this crate! This is already a lot nicer than error-chain.

**Comment by jbethune** [comment]
I've figured it out. All I needed was a try! (or a questionmark) when returning from foo():

```
fn foo() -> Result<Foo,Error> {
    Err( MyError{} )?
}
```

Because try!() uses the From trait internally.

**Comment by withoutboats** [comment]
Glad you figured it out! Yea, you need to cast errors using `into()` or `?`.

**Comment by dessalines** [comment]
This absolutely should be in the docs, took me forever to find it.
