### ISSUE TITLE
Export proc-macros directly from main crate

### ISSUE THREAD

**Issue by TedDriggs** [withoutboats/failure#71]
There's a trick that can export traits and proc macros from one crate. Using this would make the dependency declaration cleaner, and could be gated on a default feature for people who don't need the macros.

**Comment by withoutboats** [comment]
Can you link to the trick?

**Comment by TedDriggs** [comment]
I'm trying to find a writeup of it, but you can see it in action [here](https://github.com/TedDriggs/darling/blob/master/src/lib.rs#L56) in one of my own projects.

I believe the trick is that you can reexport proc macros, you just can't declare them locally.

**Comment by withoutboats** [comment]
Interesting! This is technically an unstable feature we accidentally allowed through on stable. I'll think about doing this.
