### ISSUE TITLE
impl<Inner> From<Inner> for Context<Inner>

### ISSUE THREAD

**Issue by est31** [withoutboats/failure#75]
I am personally trying out now a light variant of the custom [Error + ErrorKind approach](https://boats.gitlab.io/failure/error-errorkind.html), where I have an ErrorKind but instead of a custom Error I just use `type MyError = Context<MyErrorKind>;`.

This works great for the usual from impl's but it doesn't help when I want to return `try!(Err(ErrorKind::SomeKind))` directly.

Therefore I think it would be great to always have `From<Inner>` implemented for `Context<Inner>`. Right now I have to do `try!(Err(Context::new(ErrorKind::SomeKind)))` instead, or impl the from myself, but neither are nice things to do :).

**Comment by withoutboats** [comment]
I think I just didn't think about doing this! I don't think there is any coherence issue. I'm for it, and I've tagged this issue help wanted :)

**Comment by MaloJaffre** [comment]
I'm working on it!
