### ISSUE TITLE
Use Any trait instead of magical __private_get_type_id__ method for downcasting

### ISSUE THREAD

**Issue by Michael-F-Bryan** [withoutboats/failure#77]
The `Fail` trait currently has a hidden ` __private_get_type_id__()` method which gets the `TypeId` of a type to support downcasting. Would it be better to explicitly add `Any` as a trait bound to `Fail` instead of the hidden method?

```rust
pub trait Fail: Display + Debug + Send + Sync + 'static {

    ...

    #[doc(hidden)]
    fn __private_get_type_id__(&self) -> TypeId {
        TypeId::of::<Self>()
}
```

If all `Fail`s implement `Any` that also means we'll be able to avoid the pointer casting being done in `Fail::downcast_ref()` and friends and leave the responsibility of ensuring correctness to the standard library.

I'm sure you've considered this in the past seeing as the implementation of `Fail::downcast_ref()` is almost identical to the one for `Any`, so what was the justification for adding a `#[doc(hidden)]` function for allowing downcasting?

**Comment by withoutboats** [comment]
You cannot cast an `&Fail` to an `&Any`, so the downcast methods have to be written ourselves. In theory, with the Any bound, we could get `get_type_id()`, avoiding the hidden method. However, `get_type_id()` is unstable, so we cannot do that on stable Rust.
