### ISSUE TITLE
Not clear how to handle tuple-structs

### ISSUE THREAD

**Issue by spease** [withoutboats/failure#78]
#[derive(Fail)]
    enum MyError {
      #[fail(display = "The unthinkable happened: {}", 0)]
      SomeProblem(SomeData);
    }

It's not clear how to provide a fail(display) attribute for this kind of error. Trying the above, I get an error that non-string literals in attributes are experimental (issue #34981).

**Comment by withoutboats** [comment]
For now, you have to use `_0` for tuple structs. Its an ugly hack, and hopefully the attribute syntax will become more flexible soon.
