### ISSUE TITLE
`Error` has `context` but not `with_context`

### ISSUE THREAD

**Issue by epage** [withoutboats/failure#83]
[`ResultExt`](https://github.com/withoutboats/failure/blob/master/src/result_ext.rs) provides both a `context(d)` and `with_context(FnOnce(...) -> D)`, allowing for lazily evaluated contexts.

`Error` includes support for [`context(d)`](https://github.com/withoutboats/failure/blob/master/src/error.rs#L59) but not `with_context`.

**Comment by epage** [comment]
Apparently this is also true for the `Fail` trait
https://github.com/withoutboats/failure/blob/master/src/lib.rs#L109

**Comment by withoutboats** [comment]
The lazy evaluation exists on `ResultExt` to support not evaluating it in the `Ok` case. If you have an `Error` or `T: Fail`, this will always be evaluated, so lazy evaluation is not very useful.

**Comment by epage** [comment]
Fair point, didn't think that through enough :)
